### PR TITLE
CHK-482: Add rules for ARE and fix ITA number with geolocation

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What is the purpose of this pull request?

This adds specific rules for United Arab Emirates, and tweaks the rules for Italy.

#### What problem is this solving?

Fixes geolocation usage in both countries, where if you inputted an address without a number the user wouldn't be able to proceed from the shipping step.

#### How should this be manually tested?

[Workspace](https://lucas--vtexgame1geo.myvtex.com/checkout/cart/add?sku=312&qty=1&seller=1&sc=2).

You can use the following addresses:

 - United Arab Emirates: W Corniche Rd - Al Ras Al Akhdar.
 - Italy: Via del Telegrafo.

For both addresses you should be able to input a number and move forward.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by wdsrocha** [comment]
Is this bug related to your PR (see video)? Because it worked with "W Corniche Rd - Al Ras Al Akhdar", but crashed for a generic address like "Abu Dhabi"

https://user-images.githubusercontent.com/26108090/103313250-3f73b300-49fe-11eb-8c3c-2777f6658c3b.mov

**Comment by lucasecdb** [comment]
> Is this bug related to your PR (see video)? Because it worked with "W Corniche Rd - Al Ras Al Akhdar", but crashed for a generic address like "Abu Dhabi"

that is really weird.. I assume is something related to the rules I created? but I'm not sure, because the "calcular entrega" button is on omnishipping :-(

**Comment by lucasecdb** [comment]
by the way, if you attempt to clear the number input it isn't being cleared for some reason, but after I tried deleting it the shipping options appeared and the button to go to the payment step also appeared 🐛

**Review by wdsrocha — APPROVED** [review]

**Comment by wdsrocha** [comment]
Found a specific but consistent bug. It seems to happen with the following steps:
1. Check the "Sem número" checkbox (doesn't matter if the number input is filled or not)
2. Do any other `action`
3. Try to uncheck the checkbox. It should be impossible

Here are two examples:

https://user-images.githubusercontent.com/26108090/103936464-370a2f00-5106-11eb-852c-a07011f8df39.mov

**Comment by caetano1** [comment]
Hmm same as https://github.com/vtex/address-form/pull/307 -> i've tried to complete the purchase using my VTEX email (joao.caetano@vtex.com.br), delivery to the Vatican and payment method = money -> VTEX ID kept popping up to me. Is it related to this? @lucasecdb

**Review by wdsrocha — APPROVED** [review]

**Review by darlenedms — APPROVED** [review]

**Review by wdsrocha — DISMISSED** [review]

**Review by wdsrocha — APPROVED** [review]

**Review by jeffersontuc — APPROVED** [review]

**Pull request merged**
