### PR TITLE
Fix all eslint issues

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What is the purpose of this pull request?

Make this repository eslint-error-free :satisfaction:

#### What problem is this solving?

Fix all eslint issues :tada:

#### How should this be manually tested?

Run `yarn lint`, there should be no issues.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by wdsrocha** [comment]
I still get some warnings/errors :c

```
$ yarn lint
yarn run v1.22.10
$ eslint --ext js,jsx,ts,tsx .

/Users/wdsrocha/dev/vtex/misc/address-form/react/AutoCompletedFields.test.js
  109:13  warning  Use array destructuring  prefer-destructuring

/Users/wdsrocha/dev/vtex/misc/address-form/react/geolocation/Map.js
  130:15  warning  Use array destructuring  prefer-destructuring

/Users/wdsrocha/dev/vtex/misc/address-form/react/geolocation/Utils.js
  24:17  warning  Use array destructuring  prefer-destructuring

/Users/wdsrocha/dev/vtex/misc/address-form/react/geolocation/geolocationAutoCompleteAddress.js
  170:1  warning  Function 'setAddressFieldValue' has too many parameters (4). Maximum allowed is 3  max-params

/Users/wdsrocha/dev/vtex/misc/address-form/react/postalCodeFrom/SelectPostalCode.test.js
  12:9  warning  Use array destructuring  prefer-destructuring

/Users/wdsrocha/dev/vtex/misc/address-form/react/postalCodeService.js
  8:20  error  'document' is not defined  no-undef
  8:53  error  'document' is not defined  no-undef

/Users/wdsrocha/dev/vtex/misc/address-form/react/transforms/address.js
  213:11  warning  Use array destructuring  prefer-destructuring

/Users/wdsrocha/dev/vtex/misc/address-form/react/validateAddress.js
   97:8  warning  Function 'validateField' has too many parameters (4). Maximum allowed is 3       max-params
  164:1  warning  Function 'valueInOptionsMap' has too many parameters (4). Maximum allowed is 3   max-params
  176:1  warning  Function 'validateOptions' has too many parameters (4). Maximum allowed is 3     max-params
  192:1  warning  Function 'defaultValidation' has too many parameters (4). Maximum allowed is 3   max-params
  241:1  warning  Function 'validatePostalCode' has too many parameters (4). Maximum allowed is 3  max-params

✖ 13 problems (2 errors, 11 warnings)
```

I installed dependencies in both root and `react/` btw, so I'm not sure if I'm missing something

**Comment by lucasecdb** [comment]
@wdsrocha these warnings I didn't fix on purpose haha but that error shouldn't be apperaring 🤔 I'll try cloning the repo and installing the dependencies from the ground up to see if it happens here as well

**Comment by lucasecdb** [comment]
@wdsrocha fixed!

**Review by wdsrocha — DISMISSED** [review]
✨ feels good ✨

btw, the changelog wasn't added on purpose, right?

**Comment by lucasecdb** [comment]
> btw, the changelog wasn't added on purpose, right?

I was planning on releasing this... to avoid grouping these changes together with some other PR and having to revert this PR because of an unknown issue (maybe there is a bug here 🐛)

**Review by wdsrocha — APPROVED** [review]

**Review by jeffersontuc — APPROVED** [review]
:satisfaction:

**Pull request merged**
